//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrm.Framework.CI.PowerShell.Cmdlets.Common
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum ServiceEndpoint_AuthType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ACS = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HttpHeader = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HttpQueryString = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SASKey = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SASToken = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebhookKey = 4,
	}
}