//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrm.Framework.CI.PowerShell.Cmdlets.Common
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum Workflow_Category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Action = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessProcessFlow = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessRule = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dialog = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 0,
	}
}