//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrm.Framework.CI.Common.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum AsyncOperation_OperationType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActivityPropagation = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ALMAnomalyDetectionOperation = 73,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppModuleMetadataOperation = 72,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AuditPartitionCreation = 41,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkDelete = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkDeleteFileAttachment = 94,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkDeleteSubprocess = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkDuplicateDetection = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkEmail = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CalculateOrganizationMaximumStorageSize = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CalculateOrganizationStorageSize = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CalculateRollupField = 57,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CallbackRegistrationExpanderOperation = 79,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeAssign = 90,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeDelete = 91,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CheckForLanguagePackUpdates = 42,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cleanupinactiveworkflowassemblies = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CleanupSolutionComponents = 71,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CollectionOrganizationSizeStatistics = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CollectOrganizationDatabaseStatistics = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CollectOrganizationStatistics = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertDateAndTimeBehavior = 62,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Databaselogbackup = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DatabaseTuning = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DBCCSHRINKDATABASEmaintenancejob = 28,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DBCCSHRINKFILEmaintenancejob = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeletionService = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateDetectionRulePublish = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EncryptionHealthCheck = 53,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityKeyIndexCreation = 63,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EventExpanderOperation = 92,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExecuteAsyncRequest = 54,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FlowNotification = 75,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GoalRollUp = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Import = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportFileParse = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportSampleData = 38,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportSolutionMetadata = 93,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportSubprocess = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportTranslation = 59,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncomingEmailProcessing = 51,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IndexManagement = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailboxTestAccess = 52,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MassCalculateRollupField = 58,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MatchcodeUpdate = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationFullTextCatalogIndex = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutgoingActivity = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PosttoYammer = 49,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProvisionLanguagePack = 43,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuickCampaign = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringSeriesExpansion = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RefreshBusinessUnitforRecordsOwnedByPrincipal = 95,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RegenerateEntityRowCountSnapshotData = 46,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RegenerateReadShareSnapshotData = 47,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reindexallindicesmaintenancejob = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelationshipAssistantCards = 69,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResourceBookingSync = 68,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RevokeInheritedAccess = 96,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonClientMetadataOperation = 76,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SQMDataCollection = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StorageLimitNotification = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemEvent = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TransformParseData = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateContractStates = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateEntitlementStates = 56,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateKnowledgeArticleStates = 65,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateOrganizationDatabase = 44,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateSolution = 45,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UpdateStatisticIntervals = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 10,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum AsyncOperation_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceling = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pausing = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Succeeded = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Waiting = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WaitingForResources = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum BulkDeleteOperation_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceling = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Paused = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pausing = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Retrying = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Succeeded = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Waiting = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WaitingForResources = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ComponentState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeletedUnpublished = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ComponentType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIConfiguration = 402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIProject = 401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIProjectType = 400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attachment = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attribute = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributeImageConfiguration = 431,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributeLookupValue = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributeMap = 47,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AttributePicklistValue = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CanvasApp = 300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ComplexControl = 64,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionRole = 63,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connector_371 = 371,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connector_372 = 372,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContractTemplate = 37,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertRule = 154,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertRuleItem = 155,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomControl = 66,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomControlDefaultConfig = 68,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataSourceMapping = 166,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DisplayString = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DisplayStringMap = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateRule = 44,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateRuleCondition = 45,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailTemplate = 36,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityAnalyticsConfiguration = 430,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityImageConfiguration = 432,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityKey = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityMap = 46,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRelationship = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRelationshipRelationships = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRelationshipRole = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnvironmentVariableDefinition = 380,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnvironmentVariableValue = 381,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldPermission = 71,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldSecurityProfile = 70,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Form = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HierarchyRule = 65,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportMap = 208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Index = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KBArticleTemplate = 38,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LocalizedLabel = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailMergeTemplate = 39,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManagedProperty = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobileOfflineProfile = 161,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobileOfflineProfileItem = 162,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptionSet = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organization = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginAssembly = 91,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PluginType = 90,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Privilege = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrivilegeObjectTypeCode = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Relationship = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelationshipExtraCondition = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Report = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportCategory = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportEntity = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReportVisibility = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonCommand = 48,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonContextGroup = 49,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonCustomization = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonDiff = 55,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonRule = 52,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RibbonTabToCommandMap = 53,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Role = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RolePrivilege = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoutingRule = 150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoutingRuleItem = 151,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SavedQuery = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SavedQueryVisualization = 59,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessage = 201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessageFilter = 202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessagePair = 203,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessageProcessingStep = 92,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessageProcessingStepImage = 93,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageRequest = 204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageRequestField = 205,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageResponse = 206,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageResponseField = 207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceEndpoint = 95,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SimilarityRule = 165,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SiteMap = 62,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLA = 152,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAItem = 153,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemForm = 60,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ViewAttribute = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebResource = 61,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebWizard = 210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 29,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum DependencyType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SolutionInternal = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum DocumentTemplate_DocumentType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftExcel = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftWord = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum DuplicateRule_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publishing = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum EnvironmentVariableDefinition_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum EnvironmentVariableDefinition_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Boolean = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connectionreference = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JSON = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		String = 100000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum EnvironmentVariableValue_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum PluginAssembly_AuthType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BasicAuth = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum PluginAssembly_IsolationMode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		External = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sandbox = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum PluginAssembly_SourceType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AzureWebApp = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Database = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disk = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Normal = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SdkMessageProcessingStep_InvocationSource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Child = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Internal = -1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Parent = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SdkMessageProcessingStep_Mode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Asynchronous = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Synchronous = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SdkMessageProcessingStep_Stage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinalPostoperation_Forinternaluseonly = 55,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InitialPreoperation_Forinternaluseonly = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPostoperationAfterExternalPlugins_Forinternaluseonly = 45,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPostoperationBeforeExternalPlugins_Forinternaluseonly = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPreoperationAfterExternalPlugins_Forinternaluseonly = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPreoperationBeforeExternalPlugins_Forinternaluseonly = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MainOperation_Forinternaluseonly = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Postoperation = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Postoperation_Deprecated = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preoperation = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prevalidation = 10,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SdkMessageProcessingStep_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disabled = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enabled = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SdkMessageProcessingStep_SupportedDeployment
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Both = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365ClientforOutlookOnly = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerOnly = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SdkMessageProcessingStepImage_ImageType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Both = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostImage = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreImage = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ServiceEndpoint_AuthType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ACS = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HttpHeader = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HttpQueryString = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SASKey = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SASToken = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebhookKey = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ServiceEndpoint_ConnectionMode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Federated = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Normal = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ServiceEndpoint_Contract
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EventHub = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OneWay = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queue = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queue_Persistent = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rest = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Topic = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TwoWay = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Webhook = 8,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ServiceEndpoint_MessageFormat
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BinaryXML = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Json = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TextXML = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ServiceEndpoint_NamespaceFormat
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NamespaceAddress = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NamespaceName = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ServiceEndpoint_UserClaim
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserId = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserInfo = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Solution_SolutionType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Internal = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Snapshot = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SolutionComponent_RootComponentBehavior
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Donotincludesubcomponents = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncludeAsShellOnly = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncludeSubcomponents = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SolutionHistoryData_Operation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Export = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Import = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Uninstall = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SolutionHistoryData_Status
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		End = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Start = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SolutionHistoryData_SubOperation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Delete = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Update = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Upgrade = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemForm_FormActivationState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemForm_FormPresentation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AirForm = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ClassicForm = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertedICForm = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemForm_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppointmentBook = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppointmentBookBackup = 102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Card = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dashboard = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dialog = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InteractionCentricDashboard = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Main = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MainBackup = 101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MainInteractiveexperience = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MiniCampaignBO = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobileExpress = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerBIDashboard = 103,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preview = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuickCreate = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuickViewForm = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TaskFlowForm = 9,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_AccessMode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrative = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DelegatedAdmin = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noninteractive = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Read = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReadWrite = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SupportUser = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_CALType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrative = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Basic = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeviceBasic = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeviceEnterprise = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeviceEssential = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeviceProfessional = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enterprise = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Essential = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldService = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Professional = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProjectService = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sales = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Service = 10,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_EmailRouterAccessApproval
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Empty = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PendingApproval = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejected = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_IncomingEmailDeliveryMethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ForwardMailbox = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365forOutlook = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerSideSynchronizationorEmailRouter = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_InviteStatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationAccepted = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationExpired = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationNearExpired = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationNotSent = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationRejected = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationRevoked = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invited = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_OutgoingEmailDeliveryMethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365forOutlook = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerSideSynchronizationorEmailRouter = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_PreferredAddressCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailingAddress = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OtherAddress = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_PreferredEmailCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum SystemUser_PreferredPhoneCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HomePhone = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MainPhone = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobilePhone = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OtherPhone = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum WebResource_WebResourceType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Data_XML = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GIFformat = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ICOformat = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JPGformat = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PNGformat = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Script_JScript = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Silverlight_XAP = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		String_RESX = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StyleSheet_CSS = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StyleSheet_XSL = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Vectorformat_SVG = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Webpage_HTML = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_BusinessProcessType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessFlow = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TaskFlow = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_Category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Action = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessProcessFlow = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessRule = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dialog = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ModernFlow = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserved = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_Mode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Background = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Realtime = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_ProcessTriggerScope
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entity = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Form = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_RunAs
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CallingUser = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owner = 0,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_Scope
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessUnit = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organization = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ParentChildBusinessUnits = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_Stage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Postoperation = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preoperation = 20,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activated = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activation = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Definition = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Template = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Workflow_UIFlowType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Desktop = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerShell = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SeleniumIDE = 1,
	}
}
